version: "3.9"

services:
  app:
    build: ./docker
    container_name: php-mvc
    image: eojeel/php_mvc
    ports:
      - "80:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
